import 'dart:async';
import 'dart:io';

import 'package:csv/csv.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

import 'real_ble_service.dart';

class ExportService {
  static const int _maxBeatLogEntries = 10000;

  final List<Map<String, dynamic>> _beatLog = <Map<String, dynamic>>[];
  StreamSubscription<BleHeartRatePacket>? _packetSub;
  double? _lastRrMs;

  List<Map<String, dynamic>> get beatLog => List.unmodifiable(_beatLog);
  bool get isEmpty => _beatLog.isEmpty;

  void startRecording(Stream<BleHeartRatePacket> packetStream) {
    _packetSub?.cancel();
    _packetSub = packetStream.listen((pkt) {
      if (pkt.isLeadsOff || pkt.isStatusOnly) return;

      final previousRrMs = _lastRrMs;
      final isArrhythmia = previousRrMs == null
          ? false
          : (pkt.rrMs - previousRrMs).abs() > (pkt.rrMs * 0.20);
      _lastRrMs = pkt.rrMs;

      _beatLog.add({
        'timestamp': DateTime.now(),
        'hrBpm': pkt.hrBpm,
        'rrMs': pkt.rrMs,
        'isArrhythmia': isArrhythmia,
      });

      if (_beatLog.length > _maxBeatLogEntries) {
        _beatLog.removeAt(0);
      }
    });
  }

  Future<void> stopRecording() async {
    await _packetSub?.cancel();
    _packetSub = null;
  }

  Future<String> exportCsv(String patientName) async {
    if (_beatLog.isEmpty) {
      throw StateError('No data recorded yet');
    }

    final directory = await getTemporaryDirectory();
    final timestamp = DateTime.now();
    final filePath =
        '${directory.path}/kardiax_export_${_fileTimestamp(timestamp)}.csv';
    final file = File(filePath);

    final rows = <List<dynamic>>[
      ['timestamp', 'hr_bpm', 'rr_ms', 'is_arrhythmia'],
      ..._beatLog.map(
        (beat) => [
          _formatTimestamp(beat['timestamp'] as DateTime),
          beat['hrBpm'],
          (beat['rrMs'] as double).toStringAsFixed(1),
          beat['isArrhythmia'],
        ],
      ),
    ];

    final csv = const ListToCsvConverter().convert(rows);
    await file.writeAsString(csv);
    return filePath;
  }

  Future<String> exportPdf(String patientName) async {
    if (_beatLog.isEmpty) {
      throw StateError('No data recorded yet');
    }

    final directory = await getTemporaryDirectory();
    final timestamp = DateTime.now();
    final filePath =
        '${directory.path}/kardiax_export_${_fileTimestamp(timestamp)}.pdf';
    final file = File(filePath);
    final pdf = pw.Document();

    final entries = List<Map<String, dynamic>>.from(_beatLog);
    final summary = _buildSummary(entries);
    final rows = entries.length > 200
        ? entries.sublist(entries.length - 200)
        : entries;

    pdf.addPage(
      pw.MultiPage(
        pageTheme: const pw.PageTheme(
          margin: pw.EdgeInsets.all(28),
        ),
        footer: (context) => pw.Align(
          alignment: pw.Alignment.centerRight,
          child: pw.Text(
            'Generated by KardiaX - ECE 481 Senior Design',
            style: pw.TextStyle(
              color: PdfColors.grey700,
              fontSize: 9,
            ),
          ),
        ),
        build: (context) => [
          pw.Container(
            padding: const pw.EdgeInsets.symmetric(
              horizontal: 18,
              vertical: 16,
            ),
            decoration: pw.BoxDecoration(
              color: PdfColor.fromHex('0D1117'),
              borderRadius: pw.BorderRadius.circular(12),
            ),
            child: pw.Row(
              children: [
                pw.Container(
                  width: 6,
                  height: 42,
                  decoration: pw.BoxDecoration(
                    color: PdfColor.fromHex('E53935'),
                    borderRadius: pw.BorderRadius.circular(8),
                  ),
                ),
                pw.SizedBox(width: 14),
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.RichText(
                      text: pw.TextSpan(
                        children: [
                          pw.TextSpan(
                            text: 'Kardia',
                            style: pw.TextStyle(
                              color: PdfColors.white,
                              fontSize: 22,
                              fontWeight: pw.FontWeight.bold,
                            ),
                          ),
                          pw.TextSpan(
                            text: 'X',
                            style: pw.TextStyle(
                              color: PdfColor.fromHex('E53935'),
                              fontSize: 22,
                              fontWeight: pw.FontWeight.bold,
                            ),
                          ),
                        ],
                      ),
                    ),
                    pw.SizedBox(height: 3),
                    pw.Text(
                      'ECG Session Export',
                      style: pw.TextStyle(
                        color: PdfColors.grey300,
                        fontSize: 11,
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 18),
          pw.Text(
            'Patient: $patientName',
            style: pw.TextStyle(
              fontSize: 14,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            'Exported: ${_formatExportDateTime(timestamp)}',
            style: pw.TextStyle(
              color: PdfColors.grey700,
              fontSize: 11,
            ),
          ),
          pw.SizedBox(height: 18),
          pw.Text(
            'Session Summary',
            style: pw.TextStyle(
              fontSize: 15,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 10),
          pw.Wrap(
            spacing: 10,
            runSpacing: 10,
            children: [
              _summaryCard('Total beats', summary.totalBeats),
              _summaryCard('Average HR', summary.averageHr),
              _summaryCard('Min HR', summary.minHr),
              _summaryCard('Max HR', summary.maxHr),
              _summaryCard('Average RR', summary.averageRr),
              _summaryCard('Arrhythmia events', summary.arrhythmiaEvents),
            ],
          ),
          pw.SizedBox(height: 20),
          pw.Text(
            'Recent Beats',
            style: pw.TextStyle(
              fontSize: 15,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 10),
          pw.TableHelper.fromTextArray(
            headerStyle: pw.TextStyle(
              color: PdfColors.white,
              fontWeight: pw.FontWeight.bold,
              fontSize: 10,
            ),
            headerDecoration: pw.BoxDecoration(
              color: PdfColor.fromHex('1F2937'),
            ),
            cellStyle: const pw.TextStyle(fontSize: 9),
            cellAlignment: pw.Alignment.centerLeft,
            cellPadding: const pw.EdgeInsets.symmetric(
              horizontal: 8,
              vertical: 6,
            ),
            headers: const ['Time', 'HR (bpm)', 'RR (ms)', 'Rhythm'],
            data: rows
                .map(
                  (beat) => [
                    _formatTimestamp(beat['timestamp'] as DateTime),
                    '${beat['hrBpm']}',
                    (beat['rrMs'] as double).toStringAsFixed(1),
                    (beat['isArrhythmia'] as bool) ? 'Arrhythmia' : 'Normal',
                  ],
                )
                .toList(),
          ),
        ],
      ),
    );

    await file.writeAsBytes(await pdf.save());
    return filePath;
  }

  Future<void> shareFile(String filePath) async {
    final mimeType = filePath.endsWith('.pdf') ? 'application/pdf' : 'text/csv';
    final fileName = filePath.split('/').last;
    await Share.shareXFiles([
      XFile(filePath, mimeType: mimeType, name: fileName),
    ]);
  }

  ExportSummary _buildSummary(List<Map<String, dynamic>> entries) {
    final totalBeats = '${entries.length}';
    if (entries.length < 2) {
      return ExportSummary(
        totalBeats: totalBeats,
        averageHr: 'N/A',
        minHr: 'N/A',
        maxHr: 'N/A',
        averageRr: 'N/A',
        arrhythmiaEvents: 'N/A',
      );
    }

    final hrValues = entries.map((beat) => beat['hrBpm'] as int).toList();
    final rrValues = entries.map((beat) => beat['rrMs'] as double).toList();
    final arrhythmiaCount = entries
        .where((beat) => beat['isArrhythmia'] as bool)
        .length;

    final averageHr =
        (hrValues.reduce((a, b) => a + b) / hrValues.length).toStringAsFixed(1);
    final averageRr =
        (rrValues.reduce((a, b) => a + b) / rrValues.length).toStringAsFixed(1);

    return ExportSummary(
      totalBeats: totalBeats,
      averageHr: '$averageHr bpm',
      minHr: '${hrValues.reduce((a, b) => a < b ? a : b)} bpm',
      maxHr: '${hrValues.reduce((a, b) => a > b ? a : b)} bpm',
      averageRr: '$averageRr ms',
      arrhythmiaEvents: '$arrhythmiaCount',
    );
  }

  pw.Widget _summaryCard(String label, String value) {
    return pw.Container(
      width: 160,
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: pw.BorderRadius.circular(10),
        border: pw.Border.all(
          color: PdfColors.grey300,
        ),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            label,
            style: pw.TextStyle(
              color: PdfColors.grey700,
              fontSize: 10,
            ),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            value,
            style: pw.TextStyle(
              fontSize: 13,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
        ],
      ),
    );
  }

  String _fileTimestamp(DateTime timestamp) {
    final y = timestamp.year.toString().padLeft(4, '0');
    final m = timestamp.month.toString().padLeft(2, '0');
    final d = timestamp.day.toString().padLeft(2, '0');
    final h = timestamp.hour.toString().padLeft(2, '0');
    final min = timestamp.minute.toString().padLeft(2, '0');
    final s = timestamp.second.toString().padLeft(2, '0');
    return [y, m, d, '_', h, min, s].join();
  }

  String _formatTimestamp(DateTime timestamp) {
    final h = timestamp.hour.toString().padLeft(2, '0');
    final m = timestamp.minute.toString().padLeft(2, '0');
    final s = timestamp.second.toString().padLeft(2, '0');
    final ms = timestamp.millisecond.toString().padLeft(3, '0');
    return '$h:$m:$s.$ms';
  }

  String _formatExportDateTime(DateTime timestamp) {
    final y = timestamp.year.toString().padLeft(4, '0');
    final mon = timestamp.month.toString().padLeft(2, '0');
    final d = timestamp.day.toString().padLeft(2, '0');
    final h = timestamp.hour.toString().padLeft(2, '0');
    final min = timestamp.minute.toString().padLeft(2, '0');
    final s = timestamp.second.toString().padLeft(2, '0');
    return '$y-$mon-$d $h:$min:$s';
  }
}

class ExportSummary {
  final String totalBeats;
  final String averageHr;
  final String minHr;
  final String maxHr;
  final String averageRr;
  final String arrhythmiaEvents;

  const ExportSummary({
    required this.totalBeats,
    required this.averageHr,
    required this.minHr,
    required this.maxHr,
    required this.averageRr,
    required this.arrhythmiaEvents,
  });
}
