// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHMFlKVW_SnLgal7a25p7O0z67LU05PiE',
    appId: '1:549435624034:web:49efd167311a5c25971f3b',
    messagingSenderId: '549435624034',
    projectId: 'kardiax-e4788',
    authDomain: 'kardiax-e4788.firebaseapp.com',
    databaseURL: 'https://kardiax-e4788-default-rtdb.firebaseio.com',
    storageBucket: 'kardiax-e4788.firebasestorage.app',
    measurementId: 'G-YWVKQF8JGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLRR3UkH4nRKIT30BDrmaG8oQ6yQAA-LY',
    appId: '1:549435624034:android:ed2ce469da36f45c971f3b',
    messagingSenderId: '549435624034',
    projectId: 'kardiax-e4788',
    databaseURL: 'https://kardiax-e4788-default-rtdb.firebaseio.com',
    storageBucket: 'kardiax-e4788.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsL-AM3ogsiKAi6B4jaskY74DLYPjwW1g',
    appId: '1:549435624034:ios:45081a34412f7279971f3b',
    messagingSenderId: '549435624034',
    projectId: 'kardiax-e4788',
    databaseURL: 'https://kardiax-e4788-default-rtdb.firebaseio.com',
    storageBucket: 'kardiax-e4788.firebasestorage.app',
    iosBundleId: 'com.example.kardiax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsL-AM3ogsiKAi6B4jaskY74DLYPjwW1g',
    appId: '1:549435624034:ios:45081a34412f7279971f3b',
    messagingSenderId: '549435624034',
    projectId: 'kardiax-e4788',
    databaseURL: 'https://kardiax-e4788-default-rtdb.firebaseio.com',
    storageBucket: 'kardiax-e4788.firebasestorage.app',
    iosBundleId: 'com.example.kardiax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHMFlKVW_SnLgal7a25p7O0z67LU05PiE',
    appId: '1:549435624034:web:2b089638c78a13df971f3b',
    messagingSenderId: '549435624034',
    projectId: 'kardiax-e4788',
    authDomain: 'kardiax-e4788.firebaseapp.com',
    databaseURL: 'https://kardiax-e4788-default-rtdb.firebaseio.com',
    storageBucket: 'kardiax-e4788.firebasestorage.app',
    measurementId: 'G-KCJEQK8W99',
  );
}
